### PR TITLE
Fix .poly file parsing and add support for multiple polygons

### PR DESCRIPTION
**Pull request by DavidKarlas**
First problem was that latitude and longitude were reverted, so now it parses `lon` 1st
I also added support for parsing multiple polygons

### CODE REVIEW

**Comment by DavidKarlas** [comment]
Here is example:
https://download.geofabrik.de/europe/liechtenstein.poly
Download that file and try to use it on https://protomaps.com/extracts

Hopefully after this change it will work...

**Comment by bdon** [comment]
Merged! thank you, I also fixed up two test cases to handle lat/lon and multiple outer loops https://github.com/protomaps/OSMExpress/blob/master/test/test_region.cpp#L178

> Download that file and try to use it on https://protomaps.com/extracts

That site only takes GeoJSON as an input right now and .poly files won't work; do you expect to use those more often? If so I can look into adding that as an option.

**Comment by DavidKarlas** [comment]
Thank you for adding tests, I didn't notice there are tests...
Usually .poly file are more readily available like and seems more standard input for extract...
But no need to do it for me, there are websites/tools where you can do conversions easily...

I do have additional question... There is no API for https://protomaps.com/extracts right?
I'm working on tool for semi-automatic importing, where tool creates .osc file to be loaded into JOSM, and I want to apply imported data on fresh OSM data, areas is smalls <100k nodes, and this is only tool that can do the job, working on setting up my own instance, dealing mostly on how to limit updates and stuff to Slovenia...

**Comment by bdon** [comment]
There is an API, depending on your frequency and nature of use (commercial, hobby project, etc) I can grant you a key to access it - please email me brandon@protomaps.com if you would like details.

The other options are to run your own planet.osmx with minutely or daily replication from planet.openstreetmap.org, or you can use just https://download.geofabrik.de/europe/slovenia.html which has daily osm.pbf or diffs, it would be much less resources to just use a country extract instead of the planet which requires >1TB of fast disk.

**Comment by DavidKarlas** [comment]
Problem with using https://download.geofabrik.de/europe/slovenia.html is, that I want minutely updates... and there are none for Slovenia, I was planning to use europe and than pass each .osc.gz to osmconvert to filter it before passing to osmx to do updating...
Sending email soon...

**Pull request merged**
